FROM mcr.microsoft.com/playwright:v1.58.0-noble

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy test files
COPY . .

# Run tests
CMD ["npx", "playwright", "test", "--reporter=list"]
